name: publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    # setup the repository
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - run: |
        uv venv
        uv sync
        source .venv/bin/activate

    - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Build
      run: uv build

    - name: Publish
      run: uv publish
